CREATE TABLE IF NOT EXISTS conveyors (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    manager_id INT
        REFERENCES employees(id)
        ON DELETE SET NULL,
    name VARCHAR(50),
    commissioning_date DATE,
    decommissioning_date DATE
);

INSERT INTO conveyors
    (manager_id, name, commissioning_date, decommissioning_date)  
VALUES
    (0, 'Неуязвимый', TO_DATE('2023-01-01'), TO_DATE('2023-11-14')), 
    (0, 'Пельменный', TO_DATE('2023-02-01'), NULL), 
    (2, 'Универсальный', TO_DATE('2023-06-01'), NULL);

CREATE INDEX ON conveyors USING HASH (manager_id);