CREATE TABLE IF NOT EXISTS conveyors (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    manager_id INT
        REFERENCES employees(id)
        ON DELETE SET NULL,
    name VARCHAR(50),
    factory_id INT 
        REFERENCES factories(id) 
        ON DELETE SET NULL,
    commissioning_date DATE,
    decommissioning_date DATE
);

INSERT INTO conveyors
    (manager_id, name, factory_id, commissioning_date, decommissioning_date)  
VALUES
    (1, 'Неуязвимый', 1, TO_DATE('2023-01-01', 'YYYY-MM-DD'), TO_DATE('2023-11-14', 'YYYY-MM-DD')), 
    (1, 'Пельменный', 2, TO_DATE('2023-02-01', 'YYYY-MM-DD'), NULL), 
    (2, 'Универсальный', 4, TO_DATE('2023-06-01', 'YYYY-MM-DD'), NULL);

CREATE INDEX ON conveyors USING HASH (manager_id);