CREATE TABLE IF NOT EXISTS deliveries (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    transport_number VARCHAR(10)
        REFERENCES transports(transport_number)
        ON DELETE SET NULL,
    delivery_point_id INT
        REFERENCES delivery_points(id)
        ON DELETE SET NULL,
    packs_count INT CHECK(packs_count IN NULL OR packs_count >= 0),
    factory_id INT
        REFERENCES factories(id)
        ON DELETE SET NULL
)