CREATE TABLE IF NOT EXISTS delivery_points(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(255) NOT NULL,
    point_type VARCHAR(255)
        REFERENCES delivery_point_types(name)
        ON DELETE SET NULL,
    packs_capacity INT NOT NULL
)