CREATE TABLE IF NOT EXISTS factories(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(255) NOT NULL
);

INSERT INTO deliveries 
    (address) 
VALUES
    ("г. Санкт-Петербург, Кронверкский проспект, д.49"), 
    ("г. Санкт-Петербург, Биржевая линия, д.4"),
    ("г. Санкт-Петербург, Биржевая линия, д. 14-16"),
    ("г. Санкт-Петербург, Ломоносова улица д.9."),
    ("г. Санкт-Петербург, Гривцова переулок д.14-16, лит.А");
